# Generated by Django 4.0.4 on 2022-05-30 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='poly',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
