# Generated by Django 4.0.4 on 2022-05-30 18:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0002_alter_servicearea_poly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
    ]
