# Generated by Django 4.0.4 on 2022-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0006_rename_geom_servicearea_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
    ]
