# Generated by Django 4.0.4 on 2022-05-30 20:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0007_servicearea_lat_servicearea_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
