# Generated by Django 4.0.4 on 2022-05-31 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0008_alter_servicearea_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lat1',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude 1'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lat2',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude 2'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lat3',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude 3'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lat4',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude 4'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lon1',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude 1'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lon2',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude 2'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lon3',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude 3'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='lon4',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude 4'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
