# Generated by Django 4.0.4 on 2022-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0009_remove_servicearea_lat_remove_servicearea_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lat3',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lat4',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon2',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon3',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon4',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='coordinate1',
            field=models.CharField(max_length=300, null=True, verbose_name='Pair 1: Latitude and Longditude'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='coordinate2',
            field=models.CharField(max_length=300, null=True, verbose_name='Pair 2: Latitude and Longditude'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='coordinate3',
            field=models.CharField(max_length=300, null=True, verbose_name='Pair 3: Latitude and Longditude'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='coordinate4',
            field=models.CharField(max_length=300, null=True, verbose_name='Pair 4: Latitude and Longditude'),
        ),
    ]
