# Generated by Django 4.0.4 on 2022-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0010_remove_servicearea_lat1_remove_servicearea_lat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='coordinate1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pair 1: Latitude and Longditude'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='coordinate2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pair 2: Latitude and Longditude'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='coordinate3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pair 3: Latitude and Longditude'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='coordinate4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pair 4: Latitude and Longditude'),
        ),
    ]
