# Generated by Django 4.0.4 on 2022-05-31 20:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0012_remove_servicearea_coordinate1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='lon3',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitde 3'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=8, default=None, max_digits=20),
        ),
    ]
